// Auto-generated research report template for Deep Research Assistant
// Generated by reportWriter.js — do not edit manually

#set page(
  paper: "a4",
  margin: (left: 2.5cm, right: 2.5cm, top: 2.5cm, bottom: 2.5cm),
  numbering: "1",
)

#set text(
  font: ("SimSun", "Microsoft YaHei", "Times New Roman"),
  size: 11pt,
  lang: "zh",
)

#set heading(numbering: "1.")

#show heading: set text(
  font: ("SimHei", "Microsoft YaHei", "Arial"),
  weight: "bold",
)

#set par(leading: 0.65em, first-line-indent: 2em)
#set list(indent: 1.5em)

// ---- Cover Page ----
#v(4cm)
#align(center)[
  #text(size: 28pt, weight: "bold")[{{TITLE}}]
  #v(1cm)
  #text(size: 14pt, fill: rgb("#555555"))[{{TYPE}}]
  #v(1.5cm)
  #text(size: 11pt, fill: rgb("#777777"))[
    生成日期：{{DATE}}\
    #if "{{SOURCES}}" != "" [
      素材来源：{{SOURCES}} 条\
    ]
    #if "{{CITED}}" != "" [
      引用文献：{{CITED}} 条\
    ]
    方法论：多源搜索 · 交叉验证 · AI 辅助撰写
  ]
]

#pagebreak()
#outline(title: "目录", depth: 2)
#pagebreak()

// ---- Content Sections ----
{{SECTIONS}}

// ---- References ----
#pagebreak()
#heading(numbering: none)[参考文献]
#set par(first-line-indent: 0em)

{{REFERENCES}}
